version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: elimuhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: elimuhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elimuhub-network

  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: elimuhub-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/elimuhub
      JWT_SECRET: your-production-jwt-secret-here
      JWT_REFRESH_SECRET: your-production-refresh-secret-here
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/logs:/app/logs
    depends_on:
      - postgres
    networks:
      - elimuhub-network

  # Frontend React Application
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5000/api
    container_name: elimuhub-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - elimuhub-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: elimuhub-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - elimuhub-network
    profiles:
      - production

volumes:
  postgres_data:
    driver: local

networks:
  elimuhub-network:
    driver: bridge